vich_uploader:
    db_driver: orm
    mappings:
        upload_carrousel:
            uri_prefix: '%images/upload_carrousel
            upload_destination: '%upload_carrousel%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false