vich_uploader:
    db_driver: orm

    mappings:
        upload_background:
            uri_prefix: '%upload_background%'
            upload_destination: '%kernel.project_dir%/public%upload_background'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false

    mappings:
        upload_carrousel:
            uri_prefix: '%upload_carrousel%'
            upload_destination: '%kernel.project_dir%/public%upload_carrousel'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false