vich_uploader:
    db_driver: orm
    mappings:
        images:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false